apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: code-generator
  template:
    metadata:
      labels:
        app: code-generator
    spec:
      containers:
      - name: code-generator
        image: microsoft/azure-vote-front:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: code-generator
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: code-generator

